services:
  backend:
    build: ./backend
    container_name: ihc-backend
    ports:
      - "8005:8000"
  frontend:
    build: ./frontend
    container_name: ihc-frontend
    ports:
      - "3005:3005"
    environment:
      - VITE_API_BASE=http://134.209.126.22:8005
