version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8005:8000"
    volumes:
      - ./backend:/app
      - ./backend/database.db:/app/database.db  # ← Agregar esta línea
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    ports:
      - "3005:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://134.209.126.22:8005
    depends_on:
      - backend